version: '3'
services:
  redis:
    image: "redis:alpine"
    container_name: redis

  iot_health_simulator:
    build: ./iot_health_simulator
    container_name: iot_health_simulator
    depends_on:
      - redis

  ai_health_predictor:
    build: ./ai_health_predictor
    container_name: ai_health_predictor
    depends_on:
      - redis

  dashboard:
    build: ./dashboard
    container_name: dashboard
    ports:
      - 3000:3000
    depends_on:
      - redis
